
name: Docker hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:  
    runs-on: ubuntu-latest
    steps:     
        - name: Checkout 
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          
#         - name: Grant execute permission for gradlew
#           run: chmod +x gradlew

#         - name: Build with Gradle
#           run: ./gradlew build

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/my-project:latest
