# This is a basic workflow to help you get started with Actions

name: elastic log

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: checkout
       uses: actions/checkout@v2
     - name: build
       run: this-will-fail
     - name: elastic-logs
       if: failure()
       uses: masci/elastic-logs@v1
       with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
#          cloud-id: ${{ secrets.CLOUD_ID }}
#          username: ${{ secrets.ES_USER }}
#          password: ${{ secrets.ES_PASS }}
         job-names: build
